#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$birthDate = '1984-01-16';

$days = new \Morozov\Dates\BirthDays($birthDate);

$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";

